# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: King Mui
subtitle: 用艺术的眼光发现技术的美
description: 生命不息，学习不止
keywords: "前端开发,front-end,javascript,typescript,dart,react,vue,flutter,node,deno,open-source,Developer,Programmer,Coder,html,css"
author: King Mui
language: zh-CN
timezone: Asia/Shanghai # 网站时区。Hexo 默认使用您电脑的时区。
email: kingmui.dev@outlook.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.kingmui.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source # 资源文件夹，这个文件夹用来存放内容。
public_dir: public # 公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags # 标签文件夹
archive_dir: archives # 归档文件夹
category_dir: categories # 分类文件夹
code_dir: downloads/code # Include code 文件夹
i18n_dir: :lang # 国际化（i18n）文件夹
skip_render: README.md # 跳过指定文件的渲染，您可使用 glob 表达式来匹配路径。

# Writing
new_post_name: :title.md # 新文章的文件名称
default_layout: post # 预设布局
auto_spacing: true # 在中文和英文之间加入空格
titlecase: false # 把标题转换为 title case
# 在新标签中打开链接
external_link:
  enable: true
filename_case: 0 # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false # 显示草稿
post_asset_folder: false # 启动 Asset 文件夹
relative_link: false # 把链接改为与根目录的相对位址
future: true # 显示未来的文章
highlight: # 代码块的设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map: # 分类别名
tag_map: # 标签别名

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10 # 每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page # 分页目录

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@github.com:kingmui/kingmui.github.io.git
  branch: master
  message: Update
  name: kingmui
  email: kingmui.dev@outlook.com
- type: baidu_url_submitter

# -------------- other config --------------

# hexo sitemap 网站地图
sitemap:
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

baidu_url_submit:
  count: 1000 # 提交最新的一个链接
  host: kingmui.cn # 在百度站长平台中注册的域名
  token: LsmiHvTO2rSVe2KQ # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt

nofollow:
  enable: true
  exclude:
    - kingmui.cn

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# 本地搜索
## https://theme-next.js.org/docs/third-party-services/search-services.html
search:
  path: search.xml
  field: post
  content: true
  format: html

comments:
  lazyload: true
